site_name: Generator-Bro
pages:
- ['index.md', 'Home']
- ['install.md', 'Install']
- ['generators.md', 'Generators']
- ['development.md', 'Development']
- ['sponsors.md', 'Sponsors']
- ['contributing.md', 'Contributing']
theme: readthedocs
markdown_extensions: [admonition]